version: '3'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:     
      POSTGRES_DB: postgres     
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: postgres     
      POSTGRES_HOST_AUTH_METHOD: trust     
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  web:
    image: tapage-l-seut 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:     
      SQL_ENGINE: django.db.backends.postgresql_psycopg2
      SQL_DATABASE: postgres
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    ports:
            - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

