# Generated by Django 2.0.4 on 2018-05-18 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'édito")),
                ('contenu', models.TextField()),
            ],
            options={
                'verbose_name': 'Edito',
                'ordering': ['date'],
            },
        ),
    ]
