# Generated by Django 2.1.15 on 2020-04-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tapage', '0003_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='photosss',
        ),
        migrations.RenameField(
            model_name='photosss',
            old_name='photo',
            new_name='photosss',
        ),
    ]
