# Generated by Django 2.1.15 on 2020-04-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_tapage', '0004_auto_20200413_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosss',
            name='photosss',
            field=models.ImageField(upload_to='gallery', verbose_name='my_photo'),
        ),
    ]
