# Generated by Django 2.0 on 2020-09-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_tapage', '0005_auto_20200413_2056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photosss',
        ),
    ]
